# -*- coding: utf-8 -*-
"""Project_un-supervised_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBqpS5fDujmA8JImQJLe_A9M8vNgOWU1
"""

# Keep a log for all the actions performed
import logging
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("CareerDrive_EDA")

logger.info("LOG CAT IS NOW ACTIVE. ALL SYSTEMS GREEN.")



import pandas as pd
import numpy as np
import re
import nltk
import logging
import seaborn as sns
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity
from collections import Counter
from itertools import combinations

import scipy.cluster.hierarchy as sch


import networkx as nx

from wordcloud import WordCloud

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("CareerDrive_EDA")

nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Define the central data repository path.
file_path = '/content/Career Drive Project Data Sources.xlsx'


# DATA INGESTION & NOISE REDUCTION

# Load the three datasets (from Excel as dataFrames) - Construction ONet Codes, Community College Programs, Umaine Programs
logger.info("Loading Excel sheets...")
onet_data_raw = pd.read_excel(file_path, sheet_name='Construction ONet Codes')
community_college = pd.read_excel(file_path, sheet_name='Community College Programs')
umaine_programs = pd.read_excel(file_path, sheet_name='Umaine Programs')

# Data Cleaning for ONet Codes:
# Remove rows without ONET CODE
# Use a Regular Expression (r'\d') to only keep rows with valid digits
onet_data_cleaned = onet_data_raw.dropna(subset=['ONET CODE']).copy()
onet_data_cleaned = onet_data_cleaned[onet_data_cleaned['ONET CODE'].astype(str).str.contains(r'\d', na=False)]


# PREPROCESSING - to prepare text for TF-IDF Vectorization

def preprocess_text(text):

    if not isinstance(text, str): return

    # Lowercase conversion
    text = text.lower()

    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)

    # Tokenization
    tokens = text.split()

    # Remove stop wordsand Lemmatization
    cleaned = [lemmatizer.lemmatize(w) for w in tokens if w not in stop_words]

    # Re-join tokens into a single 'Skill Document'.
    return " ".join(cleaned)

# Create the 'Master Skill Document' for each job role
# We combine the Title, Roles, and Keywords for clustering
onet_data_cleaned['cleaned_text'] = (onet_data_cleaned['Title'].fillna('') + " " +
                                  onet_data_cleaned['Key Roles'].fillna('') + " " +
                                  onet_data_cleaned['Key Words'].fillna('')).apply(preprocess_text)

logger.info("NLP Preprocessing complete")

# CLUSTERING & DIMENSIONALITY REDUCTION

logger.info("Running Clustering...")

# TF-IDF (Term Frequency-Inverse Document Frequency) Vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(onet_data_cleaned['cleaned_text'])

# K-Means Clustering - 3 clusters
model = KMeans(n_clusters=3, random_state=42, n_init=10)
onet_data_cleaned['Cluster'] = model.fit_predict(tfidf_matrix)

# PCA Principal Component Analysis
pca = PCA(n_components=2)
pca_results = pca.fit_transform(tfidf_matrix.toarray())
onet_data_cleaned['PCA1'], onet_data_cleaned['PCA2'] = pca_results[:, 0], pca_results[:, 1]

# Visualization of Job Clusters
plt.figure(figsize=(10, 6))
sns.scatterplot(data=onet_data_cleaned, x='PCA1', y='PCA2', hue='Cluster', style='Sector', s=100, palette='deep')
plt.title("ONet Skill Clusters: PCA Visualization")
plt.show()



# BRIDGE ROLE ANALYSIS (TALENT PIVOTS)
logger.info("Identifying Bridge Roles...")

# Identify the 'Management' cluster by finding where 'Manager' titles appear most
mask_mgmt = onet_data_cleaned['Title'].str.contains('Manager|Management', case=False, na=False)
mgmt_cluster_id = onet_data_cleaned[mask_mgmt]['Cluster'].mode()[0] if mask_mgmt.any() else 0

# Dynamically find the Trade Cluster
all_clusters = set(onet_data_cleaned['Cluster'].unique())
other_clusters = list(all_clusters - {mgmt_cluster_id})

# To check which of the remaining clusters contains 'Highway' or 'Maintenance'
mask_trade = onet_data_cleaned['Title'].str.contains('Highway|Maintenance|Equipment', case=False, na=False)
if mask_trade.any():
    trade_cluster_id = onet_data_cleaned[mask_trade]['Cluster'].mode()[0]
else:
    trade_cluster_id = other_clusters[0] # Fallback to the first non-management cluster

logger.info(f"Dynamic Detection: Mgmt Cluster={mgmt_cluster_id}, Trade Cluster={trade_cluster_id}")


# Calculate the Management Centroid
mgmt_vectors = tfidf_matrix[(onet_data_cleaned['Cluster'] == mgmt_cluster_id).values]
mgmt_centroid = np.asarray(mgmt_vectors.mean(axis=0))

# Calculate Cosine Similarity
trade_mask = (onet_data_cleaned['Cluster'] == trade_cluster_id).values
trade_vectors = tfidf_matrix[trade_mask]
similarities = cosine_similarity(trade_vectors, mgmt_centroid).flatten()

# Create the "Bridge Role" Leaderboard
bridge_df = pd.DataFrame({
    'Title': onet_data_cleaned[trade_mask]['Title'],
    'Similarity_to_Mgmt': similarities
}).sort_values(by='Similarity_to_Mgmt', ascending=False)

print("\n Top Bridge Roles (Trade to Management)")
print(bridge_df.head(3))



logger.info("Analyzing Skill DNA...")

# Extract keyword pairs to find skills, grouped together in Maine construction roles
keyword_series = onet_data_cleaned['Key Words'].fillna('').str.lower().str.split(', ')
co_occur = Counter()

for k_list in keyword_series:
    clean_list = [k.strip() for k in k_list if k.strip()]
    # Use combinations - find word pairs that appear in the same job description
    for combo in combinations(sorted(clean_list), 2):
        co_occur[combo] += 1

print("\n Co-occurrence")
for (s1, s2), count in co_occur.most_common(5):
    print(f"{s1} + {s2}: found in {count} roles")



# UNIFIED DATA INTEGRATION
logger.info("Integrating Industry and Educational Data...")

# Same preprocessing of data from school programs (Community College & UMaine)
community_college_processed = community_college.copy()
community_college_processed['Title'] = community_college_processed['Program Name/Focus']
community_college_processed['cleaned_text'] = community_college_processed['Title'].apply(preprocess_text)
community_college_processed['type'] = 'Education'

df_um_clean = umaine_programs.copy()
df_um_clean['Title'] = df_um_clean['Program Name']
df_um_clean['cleaned_text'] = df_um_clean['Title'].apply(preprocess_text)
df_um_clean['type'] = 'Education'

onet_data_cleaned['type'] = 'Job'

# Join all sources into a single Unified Dataset
unified_data = pd.concat([
    onet_data_cleaned[['Title', 'cleaned_text', 'type']],
    community_college_processed[['Title', 'cleaned_text', 'type']],
    df_um_clean[['Title', 'cleaned_text', 'type']]
], ignore_index=True)

# Create a unified TF-IDF Matrix for the entire ecosystem.
vectorizer_merged = TfidfVectorizer(stop_words='english')
tfidf_matrix_merged = vectorizer_merged.fit_transform(unified_data['cleaned_text'].fillna(''))

# Calculate Alignment Matrix - to find training matches
job_indices = unified_data[unified_data['type'] == 'Job'].index
edu_indices = unified_data[unified_data['type'] == 'Education'].index
sim_matrix = cosine_similarity(tfidf_matrix_merged[job_indices], tfidf_matrix_merged[edu_indices])

# Calculate the Distance Matrix (1 - similarity)
dist_matrix = 1 - cosine_similarity(tfidf_matrix)

# Create the Linkage (Ward's method minimizes variance)
linkage_matrix = sch.linkage(dist_matrix, method='ward')

# Plot the Dendrogram
plt.figure(figsize=(12, 10))
dendrogram = sch.dendrogram(
    linkage_matrix,
    labels=onet_data_cleaned['Title'].values,
    orientation='left',
    leaf_font_size=10,
    color_threshold=1.5 # Adjusts the color-coding of branches
)

plt.title('Construction Career Hierarchical Skill Tree', fontsize=16)
plt.xlabel('Dissimilarity (Distance between roles)')
plt.ylabel('Job Titles')
plt.tight_layout()
plt.show()



# Load the General Job Websites Data
job_websites_df = pd.read_excel(file_path, sheet_name='General Job Websites')

# Create the Graph
construction_graph = nx.Graph()

for _, row in job_websites_df.iterrows():
    organization_name = str(row['Organizations'])
    focus_area = str(row['Focus'])
    edge_category = str(row['Category'])

    # Add nodes with 'attributes' for coloring
    construction_graph.add_node(organization_name, type='Organization')
    construction_graph.add_node(focus_area, type='Focus Sector')

    # Create the connection
    construction_graph.add_edge(organization_name, focus_area, label=edge_category)

# Calculate "Degree Centrality"
degree_centrality_scores = nx.degree_centrality(construction_graph)
logger.info("Ecosystem Centrality calculated.")

# Visualization
plt.figure(figsize=(15, 12))
node_positions = nx.spring_layout(construction_graph, k=0.5, seed=42)

graph_node_colors = []
for node, attrs in construction_graph.nodes(data=True):
    if attrs.get('type') == 'Organization':
        graph_node_colors.append('skyblue')
    else:
        graph_node_colors.append('lightgreen')

nx.draw(construction_graph, node_positions, with_labels=True,
        node_color=graph_node_colors,
        node_size=[v * 10000 for v in degree_centrality_scores.values()], # Size based on importance
        font_size=9,
        edge_color='gray',
        alpha=0.7)

plt.title("Maine Construction Ecosystem: Recruitment Hubs & Focus Areas", fontsize=16)
plt.show()

# Print the top Hubs
top_recruitment_hubs = sorted(degree_centrality_scores.items(), key=lambda x: x[1], reverse=True)[:5]
print("TOP RECRUITMENT HUBS")
for hub, score in top_recruitment_hubs:
    print(f"{hub}: {score:.2f}")



# WORD CLOUDS

# Create Word Clouds to 'see' the dominant keywords and assign human-readable
# names for those clusters (e.g., 'The Builders' vs. 'The Managers')

for i in range(3):
    # Filter the dataframe for current cluster and join all cleaned text into one large string
    text = " ".join(onet_data_cleaned[onet_data_cleaned['Cluster'] == i]['cleaned_text'])

    # Configure the WordCloud object
    wordcloud = WordCloud(width=800, height=400, background_color='white', colormap='viridis').generate(text)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.title(f"Cluster {i} Skill Profile", fontsize=16)

    # Removing axis ticks
    plt.axis('off')
    plt.show()




# EMPLOYER MARKET ANALYSIS (AGC MEMBER LIST)

# 'Data Munging' on the AGC Member list to ensure correct data alignment

# Load raw data without a header
raw_agc_members_df = pd.read_excel(file_path, sheet_name='AGC Member list ', header=None)

# Header Promotion Logic:
# We identify the 4th row (index 3) as the actual row containing column names (e.g., 'Type', 'Member Name')
agc_header_row = raw_agc_members_df.iloc[3].astype(str).tolist()

# Column Name Sanitization to ensure df['Type'] calls work correctly.
agc_header_row = [col.strip().replace('nan', '') for col in agc_header_row]
raw_agc_members_df.columns = agc_header_row

# Discard the first 4 rows (the metadata and the header itself) and reset the index
cleaned_agc_members_df = raw_agc_members_df[4:].reset_index(drop=True)

# Drop any columns imported as empty strings
cleaned_agc_members_df = cleaned_agc_members_df.loc[:, cleaned_agc_members_df.columns != '']



# CATEGORICAL DISTRIBUTION

# Visualize the distribution of Employer Types to provide the 'Market Context'

if 'Type' in cleaned_agc_members_df.columns:
    # Calculate frequencies of employer category
    agc_employer_type_counts = cleaned_agc_members_df['Type'].value_counts()

    plt.figure(figsize=(10, 6))
    agc_employer_type_counts.plot(kind='bar', color='skyblue')
    plt.title("Distribution of Maine AGC Employers by Type")
    plt.ylabel("Number of Companies")
    # Rotate labels 45 degrees to prevent overlapping of long category names
    plt.xticks(rotation=45)
    plt.show()

    # Print the raw counts for the 'Employer Market Summary'
    print("Employer Market Summary")
    print(agc_employer_type_counts)
else:
    print(f"Error: 'Type' column not found after processing. Available columns: {cleaned_agc_members_df.columns.tolist()}")

# LINGUISTIC VERB EXTRACTION

import spacy
# Load the 'Spacy' NLP Engine
try:
    # Part-of-Speech tagging
    nlp = spacy.load("en_core_web_sm")
except:
    !python -m spacy download en_core_web_sm
    nlp = spacy.load("en_core_web_sm")

def extract_verbs(text):
  # Processes text and returns only the root verbs

    doc = nlp(text)
    return " ".join([token.lemma_ for token in doc if token.pos_ == "VERB"])

# Prepare Raw Context for Tagging
if 'raw_combined_text' not in onet_data_cleaned.columns:
    onet_data_cleaned['raw_combined_text'] = (onet_data_cleaned['Title'].fillna('') + " " +
                                     onet_data_cleaned['Key Roles'].fillna('') + " " +
                                     onet_data_cleaned['Key Words'].fillna(''))

# Create 'Action DNA' Word Clouds
for i in range(3):
    cluster_raw_text_content = " ".join(onet_data_cleaned[onet_data_cleaned['Cluster'] == i]['raw_combined_text'])

    # Run Linguistic extraction
    extracted_verbs = extract_verbs(cluster_raw_text_content)

    # Check if any verbs were found to - avoid empty plot errors
    if extracted_verbs.strip():
        action_word_cloud = WordCloud(width=800, height=400, background_color='green', colormap='Blues').generate(extracted_verbs)

        plt.figure(figsize=(10, 5))
        plt.imshow(action_word_cloud)
        plt.title(f"Cluster {i}: Action DNA (What the job is about)", fontsize=16)
        plt.axis('off')
        plt.show()
    else:
        print(f"Cluster {i} has no distinct verbs detected.")

